### PR TITLE
Changed the Keep Alive strategy for User Websocket Stream.

### LINKED ISSUE #119: User data stream not working intermittently.
The userdata stream does not work some times. The main problem is, we dont get any error message from the server to identify the disconnect. Suddenly things start failing and nothing works. Can you please suggest a fix for this?

I dont see any error response from the server to handle this case.

### PR DESCRIPTION
**Pull request by coire1**
According to Docs every 30 minutes the User Websocket Stream can be
keeped alive using `PUT /api/v1/userDataStream`, keeping the same
`listenKey`. This should resolve #119.

### CODE REVIEW

**Comment by sammchardy** [comment]
Hi @coire1, this seems to ignore when the listen key changes. The listen key is part of the websocket endpoint.

I think what I'm not currently doing is passing the current listen key to `stream_get_listen_key`

**Comment by coire1** [comment]
Hi @sammchardy, first of all, thank you for your work.
I think that the `listen_key` is not supposed to change if the socket is not closed. It changes on new connections.
According to the docs, keep the socket alive just needs a PUT to `/api/v1/userDataStream`, (if I'm not missing something). I'm currently using my version smoothly from about 9 hours.

**Comment by sammchardy** [comment]
Hi @coire1 yes that is what the docs say but they haven't been updated I don't think.

I probably should have saved the chat from a while back where Ninj0r was talking about it. He recommended using POST to keep it alive, if the key changed then a new connection should be made.

What I might do is update this branch to send the listen key like you are doing, but keep in the check for the listen key changing, would you be able to test that?

**Comment by coire1** [comment]
Hi @sammchardy, sorry for the late reply, I had a busy day. I don't understand if I have to restore the check for the listen key change and test it together with my version, or just keep testing my version.
However I asked to Ninj0r on the Telegram channel how this stuff must be implemented (still waiting for a reply).
Feel free to ask for tests or related stuff.

**Comment by scoshil** [comment]
Sorry not sure if same issue but how are we meant to handle the 24 hr Binance auto-disconnect? Does the library automatically handle it or do we have to create a new connection?
@sammchardy @coire1

**Comment by coire1** [comment]
Hi @scoshil, this PR is referred to the user stream, not the public websockets. Read [this issue](https://github.com/sammchardy/python-binance/issues/122) to solve your problem!

**Comment by scoshil** [comment]
@coire1 thanks but I should have been clearer - the symptoms i'm having are actually the same as the OP in issue 119 - (https://github.com/sammchardy/python-binance/issues/119), however it seems to happen after a random amount of time (without an error message), so I was wondering whether this PR would fix it

**Pull request merged**
