### PR TITLE
Added Vanilla Options Support

### PR DESCRIPTION
**Pull request by Ollie-Hooper**
Implements support for Binance's new vanilla options product. Their API documentation can be found [here](https://binance-docs.github.io/apidocs/voptions/en/#general-info).

This PR adds all the current REST endpoints, websockets for vanilla options and an OptionsDepthCacheManager. It also adds vanilla options testnet support in both REST and websockets however I have been unable to fully verify the websocket implementation as there has been no activity on the testnet platform. It does make a successful connection however so probably would work.

### CODE REVIEW

**Comment by guillemavila** [comment]
Resolves #722

**Review by sammchardy — COMMENTED** [review]
Is there a need for a new OptionsDepthCacheManager class, it seems to be a simpler version of the superclass without re-using functionality.

**Comment by Ollie-Hooper** [comment]
Managing the depth cache works differently with the options API as on connection to the websocket they send the initial order book thus there is no poll to the depth REST endpoint. Unfortunately that meant I had to change quite a few of the main functions of the manager class however it still uses 3 of the functions of the superclass (get_depth_cache, close and get_symbol).

**Comment by faileon** [comment]
This is great, I was planning on doing this (#722), but my primary work occupied me for the past few weeks, leaving no time for open source activity. Can we hope for a PR merge soon? I'd like to test and use these new functions. Thanks @Ollie-Hooper for the effort.

**Comment by sammchardy** [comment]
I created a base class using the simpler version of the DepthCache and have merge into master.

**Pull request merged**
