### PR TITLE
fix None params

### PR DESCRIPTION
**Pull request by akgnah**
Modify the location of `_order_params`, it looks like this is the better way.  #808

### CODE REVIEW

**Comment by akgnah** [comment]
Update: fix KeepAliveWebsocket not working

Because `KeepAliveWebsocket` is passed a `client` of type `binance.Client`, we should not use the `await self._client` syntax.

**Comment by sammchardy** [comment]
@akgnah thanks for the updates and testing everything out.

Can I ask that you please keep each pull request to a specific issue.

The `BinanceSocketManager` should be passed an `AsyncClient` that's why it has the awaits. The class is asynchronous so this needs to be the case.

The request params need to match what goes into the signature, so applying a solution separate to that may also cause problems. I have pushed an update to remove `None` values inside the `_order_params` function

**Comment by akgnah** [comment]
I apologize for mixing in multiple issues in one PR, I'm new at this.

If `BinanceSocketManager` should be passed an `AsyncClient`, then the comment of the source should be modified.

If you will fix it, then I close the PR.

Thank you for your work.

**Comment by sammchardy** [comment]
Have updated docs and added typing to help here.

**Comment by akgnah** [comment]
Amazing work. Close the PR.

**Pull request closed without merging**
