### PR TITLE
Added Futures Prices Websocket

### PR DESCRIPTION
**Pull request by jiyoungsin**

### CODE REVIEW

**Comment by kimchirichie** [comment]
additive code & functional. looks good to me

**Comment by kimchirichie** [comment]
will merge in once a few people can confirm its functionality

**Comment by CyrilleBoullier** [comment]
Hello, do you know when you will merge this branch?

will futures prices be available also for the branch feature/asyncio?

Thanks,
Cyrille.

**Comment by kimchirichie** [comment]
i think this one is pretty safe to merge. all additive code. @CyrilleBoullier would you be able to test this branch and confirm it works?

**Comment by CyrilleBoullier** [comment]
Yes, if you add it also in the branch feature/asyncio then I can test it as I'm using it 24h/24h with a set of 4 cryptos.

Regards,
Cyrille.

**Comment by kimchirichie** [comment]
@CyrilleBoullier I may be confused, but `feature/asyncio` is unrelated to this branch. I will merge this one in since its only additive and will not effect any existing users.

**Pull request merged**
