### PR TITLE
streams: futures_multiplex replace socket_name fix

### LINKED ISSUE #875: Futures websocket: options_multiplex_socket() got an unexpected keyword argument 'futures_type'
It seems that there is an error in the `start_futures_multiplex_socket()` function.

the socket_name is written as `options_multiplex_socket` instead of `futures_multiplex_socket`
This leads to an error when running the multiplex socket: `options_multiplex_socket() got an unexpected keyword argument 'futures_type'`

https://github.com/sammchardy/python-binance/blob/30efaffc303a55855889a607879e9ca0eacb5221/binance/streams.py#L1226

Please change it asap as it's a critical error

### PR DESCRIPTION
**Pull request by AurelReb**
fixes #875

### CODE REVIEW

**Comment by pavs94** [comment]
This needs to be merged urgently.

**Comment by AurelReb** [comment]
As a temporary workaround in your code, you can write this:
```python
from binance import ThreadedWebsocketManager
from binance.enums import FuturesType
# temp fix of start_futures_multiplex_socket method
class ThreadedWebsocketManagerFixed(ThreadedWebsocketManager):
    def start_futures_multiplex_socket(
        self, callback, streams, futures_type=FuturesType.USD_M
    ) -> str:
        return self._start_async_socket(
            callback=callback,
            socket_name='futures_multiplex_socket',
            params={
                'streams': streams,
                'futures_type': futures_type
            }
        )
```

**Comment by sammchardy** [comment]
thanks @AurelReb

**Comment by AurelReb** [comment]
@sammchardy Could you update the library to a new release? v1.0.11

**Pull request merged**
