### PR TITLE
#941 added futures klines stream

### PR DESCRIPTION
**Pull request by MarCorCon**
An endpoint for futures klines has been added. 

- The endpoint subscribes to the binance futures klines. 

- It works with USD-M, COIN-M. 

- It works also for the contract types perpetual, current quarter and next quarter.

- Added an enum for contract types

### CODE REVIEW

**Comment by bogerv** [comment]
there is a problem in streams.py file (function start_kline_futures_socket).
needs to be modified
`params={
                'symbol': symbol,
                'interval': interval,
                'futures_type': futures_type,
                'contract_type': contract_type
}
`
to
`params={
                'symbol': symbol,
                'interval': interval,
                'futures_type': futures_type,
                'contract_type': contract_type.value
}
`

**Comment by MarCorCon** [comment]
> there is a problem in streams.py file (function start_kline_futures_socket).
> needs to be modified
> `params={ 'symbol': symbol, 'interval': interval, 'futures_type': futures_type, 'contract_type': contract_type } `
> to
> `params={ 'symbol': symbol, 'interval': interval, 'futures_type': futures_type, 'contract_type': contract_type.value } `

Do I have to do the same for 'futures_type': futures_type  => 'futures_type': futures_type.value ?

**Comment by bogerv** [comment]
> Do I have to do the same for 'futures_type': futures_type => 'futures_type': futures_type.value ?
> 
> I edited for both enums.
> 
> Although it works the same without the 'value'. I also see that in other parts of the code the enums don't have the 'value'.
> Has this behavior changed on some Python version? (I am quite new to Python.)

For futures_type this enum is used for comparison, so it does not need to add ".value"
But contract_type will use enum's value to splice btcusdt_perpetual@continuousKline_5m
If you use the enumerated type directly, the result will be
btcusdt_ContractType.perpetual@continuousKline_5m

**Comment by sammchardy** [comment]
Thanks @MarCorCon

**Comment by renruojos** [comment]
Hi,

I am switching to use ThreadedWebsocketManager() and found that my callback wasn't called for futures_kline at all.  It works for SPOT.  Sample codes below. Can someone help?

```
import time

from binance import ThreadedWebsocketManager, AsyncClient
from binance.enums import FuturesType, ContractType


def main():
    twm = ThreadedWebsocketManager()
    twm.start()

    def handle_socket_message(msg):
        if msg['e'] == 'kline':
            final_bar = msg['k']['x']
            if final_bar:
                print(msg)

    twm.start_kline_futures_socket(callback=handle_socket_message, symbol='BTCUSDT', interval='1m')
    twm.start_kline_socket(callback=handle_socket_message, symbol='GALAUSDT', interval='1m')
    twm.start_kline_socket(callback=handle_socket_message, symbol='ADAUSDT', interval='1m')
    twm.join()

	
if __name__ == "__main__":
   main()
```

**Pull request merged**
