### PR TITLE
Add fetching of first valid timestamp for symbol and interval

### PR DESCRIPTION
**Pull request by cmollen**
When getting historical klines with e.g. `KLINE_INTERVAL_1MINUTE`, it can take a large number of requests before any data is found, as the main loop tries consecutive 500 minute intervals. This change spends one request establishing the time data becomes available, which also allows for some simplifications of the main loop.

### CODE REVIEW

**Comment by sammchardy** [comment]
Thanks @cmollen this is a good idea.

**Comment by cmollen** [comment]
Sorry for submitting a PR that screwed up the unit test, although right now I'm not quite sure why the Travis CI fails on 3.6?

**Comment by sammchardy** [comment]
It's a flake8 validation issue, some whitespace you've left on line 745.

you can run `flake8 binance/` to check it yourself.

**Comment by cmollen** [comment]
Thanks for the help, @sammchardy.

**Comment by badjano** [comment]
Why isn´t @cmollen ´s method `_get_earliest_valid_timestamp `used inside `get_historical_klines` instead of that nasty while loop?

**Pull request merged**
