### PR TITLE
fixed depth cache sync in _init_cache

### PR DESCRIPTION
**Pull request by henboss**
fixed issue #418

### CODE REVIEW

**Comment by kormang** [comment]
@sammchardy Please merge this :)

**Comment by sammchardy** [comment]
@henboss @kormang can you comment the reason for this fix, happy to merge it after that.

**Comment by kormang** [comment]
What can we provide except what is mentioned in the issue?

**Comment by henboss** [comment]
I moved the initialisation of the depth cache from DepthCacheManager
constructor to inside init_cache method. Without clearing depth cache in
this way, old (and incorrect) bids and asks will stay in the depth cache
and the order book will be wrong.

**Comment by sammchardy** [comment]
Thanks @henboss

**Comment by henboss** [comment]
You’re welcome. Thanks to you for providing a great package!

**Pull request merged**
