### PR TITLE
Use ujson as deserializer over stdlib json, if possible

### PR DESCRIPTION
**Pull request by lancechua**
Hi,

Thanks for the great library.

Just a small edit to enable use of ujson over stdlib json.

Thanks again.

### CODE REVIEW

**Comment by xiaods** [comment]
FYI https://github.com/ultrajson/ultrajson

good:
UltraJSON is an ultra fast JSON encoder and decoder written in pure C with bindings for Python 2.7 and 3.5+.

bad:
dependencies another lib.

**Comment by xiaods** [comment]
@lancechua 
also you need add config here:
https://github.com/sammchardy/python-binance/blob/master/setup.py#L13

**Comment by xiaods** [comment]
apply https://github.com/sammchardy/python-binance/pull/481  pr

**Comment by kimchirichie** [comment]
closing in favor of #481

**Comment by kimchirichie** [comment]
hmm maybe this requires reopening. #481 was just adding dependency

**Comment by kimchirichie** [comment]
@oliver-zehentleitner is this okay to merge?

**Comment by oliver-zehentleitner** [comment]
i am not sure. the code is ok and also the idea behind it. 

if you look at the code you see, there is a try before the ujson import - if ujson is not available it imports the std. lib.

ujson is included in the setup.py so the next build package will automatically include ujson and the requirements.txt also includes it since a couple of days :) 

So actually the try-block doesnt make sense anymore but the import of ujson instead of json is an improvement!

I think @lancechua should rework that and then the request is fine and should get merged.

thanks for the hint with ujson! this request was the reason why i implemented it to ubwa! :+1:

**Comment by xiaods** [comment]
please merged!

**Comment by lancechua** [comment]
Glad to help! Pretty convenient that ujson also has pretty much the same API as the stdlib json. 

Updated the merge request. Let me know if this is good.

**Comment by markeyev** [comment]
Dear author, commenters,

Please pay additional attention to ujson license. It is the strictest license in the whole python-binance package. The rest of the dependencies are BSD, MIT, Apache, MPL, or PSF.

"Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer."

Is it worth it?

Thanks!

**Comment by xiaods** [comment]
@markeyev  thanks for your reminder.  Do you have another alternative recommendation?

**Comment by markeyev** [comment]
I would love to see a comparison of time spent by ujson and stdlib json on typical tasks, like reading 100-1000 messages from the WebSocket. I don't think it would be noticeable.

Another workaround is to make ujson optional, cut it off from dependencies, and add the install doc section about usjon. Like
```
try:
    import ujson as json
except ImportError:
    import json
```

**Comment by oliver-zehentleitner** [comment]
Hello!
I was not aware of this license problem. What does "redistribution of source code" exactly mean? We link to a package and use the code from a public package.... is this redistribution of source code?
On ultrajson homepage is a benchmark: https://github.com/ultrajson/ultrajson#benchmarks
orjson seams to be an interesting option and has a MIT license: https://github.com/ijl/orjson

**Comment by markeyev** [comment]
Hello Oliver, guys,

Thank you for the links! 
The license problem is not a problem yet. However, I'm not licensing expert, and my only concern is an external dependency in this particular case increasing the speed but not crucial to the work of the package itself. I would rather prefer to have an additional speed-increasing dependency optional, not mandatory.
Same for orjson or any other replacement for stdlib json. I think the most common use case for this package (correct me if I'm wrong) is not high-speed scalping, but more like swing-trading experiments.

**Comment by oliver-zehentleitner** [comment]
if something is faster, it requires less resources and i personally find the decision to choose something that is several times faster reasonable and justified. it improves the software without causing other problems. of course there are the trust aspects. this is a decision that can be made differently and depends on the philosophy of the project/community or the person in charge. for me personally it is an improvement

**Pull request merged**
