### PR TITLE
adding ujson to reqirements.txt and setup.py

### PR DESCRIPTION
**Pull request by oliver-zehentleitner**
You added ujson (https://github.com/sammchardy/python-binance/pull/383) and its missing in the requirements!

### CODE REVIEW

**Comment by xiaods** [comment]
please upgrade it. thanks a lot.

**Comment by lancechua** [comment]
Glad to see there's some interest in using a faster JSON library.  
  
I initially wanted it to be an optional requirement as I didn't want to add another dependency. ujson works very well since it has the same API to stdlib json for the most part.

**Comment by kimchirichie** [comment]
is this good to merge? need some verification from crowd before merging

**Comment by oliver-zehentleitner** [comment]
@kimchirichie 
ujson is already used by python-binance, but its missing in setup.py and requirements.txt which is needed to create the package and to install the required dependencies... ujson itself works very well and was added to python-binance code with https://github.com/sammchardy/python-binance/pull/383 . we also use it in ubwa since a couple of months....

**Pull request merged**
