### PR TITLE
Added support for stripping None-valued parameters

### PR DESCRIPTION
**Pull request by byronformwalt**
- In Client._get_earliest_valid_timestamp(), endTime is set to None, which results in a server-side error.

### CODE REVIEW

**Comment by sammchardy** [comment]
Thanks @byronformwalt

**Comment by drbh** [comment]
This is a good PR 👍

Looking forward to the merge

**Comment by Gelso22** [comment]
Hello I have the same error:
binance.exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'interval'; legal range is '^[a-zA-Z0-9]{1,36}$'

But I don't get how to fix it.. What function I have to modify? 
Sorry but I have no experience

**Comment by Talhapsycho** [comment]
> Hello I have the same error:
> binance.exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'interval'; legal range is '^[a-zA-Z0-9]{1,36}$'
> 
> But I don't get how to fix it.. What function I have to modify?
> Sorry but I have no experience

I have the same issue need help too

**Comment by smallham1** [comment]
having a similar issue when trying to withdraw. APIError(code=-1100): Illegal characters found in a parameter. is the response i get with any line that has client.withdraw in it so even a blank () or get_withdraw_history doesnt work.

**Comment by sammchardy** [comment]
Looks like this change got reverted in v1, will add it back in again.

**Comment by sammchardy** [comment]
has been fixed in v1.0.12 with tests

**Pull request merged**
