### PR TITLE
Removed dependency on dateparser.

### PR DESCRIPTION
**Pull request by ewtoombs**
Also, gave constants.py a more appropriate name, as it did not contain any enums—only string constants.

### CODE REVIEW

**Comment by sammchardy** [comment]
Thanks @ewtoombs.

Agree with a few things, 

Should remove shebangs PyCharm keeps adding them automatically. The python env line is not necessary, though I do like to keep the utf-8 encoding there. 

They are constants and not enums, and the param is essentially a string.

I did move the constants into the classes to allow for better autocomplete, and then didn't remove the enums.py file straight away to not break any existing scripts. 

Importing `from binance.enums import *` with a wildcard is easy but doesn't pass PEP8 https://www.python.org/dev/peps/pep-0008/#imports so that's what I was trying to get away from. I was possibly better just leaving them in enums.py and not being too clever. 

Any changes should be mindful of causing backward incompatible changes and justifying whether that is necessary or not.

As we support Python 2.7 using object when declaring the class isn't redundant and signifies the new style class. You're right in that Python 3 doesn't require it to be there.

**Comment by ewtoombs** [comment]
I violate PEP8 all the time. It even says you should do so whenever it doesn't make sense. (https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds) I'd call this an instance where it actually does make a lot of sense.

I had not considered the effect on pycharm though, nor pycharm's effect on the code. It's flexible software made by intelligent (intellij, lol) people, though, so I'm sure it can be reconfigured for code completion and to keep it from introducing the shebangs.

Backward compatibility will be broken, but this is still new software. No current user does not expect this.

**Comment by ewtoombs** [comment]
oh I just thought of something. The import *s in all the examples can just be replaced with import binance.constants as bc. Problem solved.

**Comment by ewtoombs** [comment]
Aw, man, we're seriously supporting python 2? Crap. Well, I just hope that's the only thing I have to do. Aw, what the Christ, seriously python 2 also needs the encoding declarations at the beginning of the file? Do we really have to support python 2? Seriously, does anybody using this library still use it?

**Comment by ewtoombs** [comment]
One of the whitespace gripes from CI actually did not violate PEP8: https://www.python.org/dev/peps/pep-0008/#id28

Specifically, whitespace around multiplication is not necessary. w/e. CI passed.

**Comment by ewtoombs** [comment]
Oh, I meant to say, the code is actually very good. Thanks for all the work you've done so far!

**Comment by sammchardy** [comment]
Hey @ewtoombs I was going to look at this, then you added a heap more.

Please split your pull requests into separate features, it is impossible to process it as it is. You have some good ideas, and your intention seems to be in the right place, and I'd like to merge some of your changes but you're not making it easy.

I'm not inclined to include anything that changes names of functions or classes potentially breaking all the scripts that existing users have running if they need to update to resolve a bug. If it's not fixing an issue or providing useful functionality then you need a good reason for me to include it :) You seemed to think it was a small unused library, but there are over 600 git clones per day, and over 4000 visits per day to the repo so there is some responsibility required.

**Comment by ewtoombs** [comment]
I actually did want to do it in multiple merge requests, but I had no idea how, at least not without waiting for the first merge request to clear before starting work on another feature. I didn't want to wait, so I just kept going. Any help here would be much appreciated.

In spite of its moderate popularity, the library is still almost brand new. Users expect things to break all the time at such an early stage. Now is the time to get the naming right. Not two years from now. All of the naming changes I did are completely reasonable for python code.

**Comment by ewtoombs** [comment]
I'm going to try to make a new pull request with the same name. If it works, I'll delete this one.

**Comment by ewtoombs** [comment]
I'm about to make a new pull request with the same name. If it works, I'll delete this one.

**Comment by ewtoombs** [comment]
New pull request succeeded: https://github.com/sammchardy/python-binance/pull/145

Closing this one now.

**Comment by ewtoombs** [comment]
Also, don't kid yourself. This library *is* small. That's just a fact. It is. And anything that doesn't have a package in the major linux distros counts as almost totally unused in my book. Finally, number of git clones is not nearly as relevant as the number of pypi installs.

**Pull request closed without merging**
