### PR TITLE
added futures accountt user socket client

### LINKED ISSUE #676: Futures user data Stream
Hello everyone,
First of all thank you the creator of this program and everyone who contributed to this program.

I am getting an error while subscribing userdatastream websockets of futures account...

I tried following changes in the code but it failed stating that APIERROR(code=0) Invalid Jason error message from Binance.

the tweaks I made to subscribe futures userdatastream are as follows:
1-In my script
bm = BinanceSocketManager(client)
def processmessage(msg):
      print(msg)
         
conn_keys = bm.start_user_socket(processmsg)
bm.start()

2. In websockets.py
in def start_socket:
I replaced stream_url with fstream_url

3. in client.py
in def create_api_uri:
I replaced api_url with futures_url

I am in need of binance futures’s userdata stream websockets....
Please help
Thanks....

### PR DESCRIPTION
**Pull request by hoseins77**
Hello,
I added the futtures user data stram
please check it out :)

Fixes #676

### CODE REVIEW

**Comment by sammchardy** [comment]
Could you rebase this with the master branch so it's easier to review the changes.

Addition of ujson should not be part of this pull request.

**Comment by hoseins77** [comment]
@sammchardy  Done :)

**Comment by sammchardy** [comment]
Awesome that's much better!

**Comment by mchangun** [comment]
Thanks, this is great! Any idea when this will make it into a release?

**Comment by sammchardy** [comment]
Have included in this in the feature/asyncio branch, please test there.

**Comment by sammchardy** [comment]
Have added these into v1.0.0 in the new asyncio format.

Please test if it's working for you.

**Comment by dnlfrst** [comment]
Is there any chance that this can be included with the new project structure since `websockets.py` has been removed?

**Comment by CalebEverett** [comment]
@hoseins77 Thanks for adding this in - could you provide an example of how to use?  I tried the following to no avail:

```python
    bm = BinanceSocketManager(client)
    async with bm._get_account_socket(path="futures") as stream:
        while websocket.client_state == WebSocketState.CONNECTED:
            res = await stream.recv()
            await websocket.send_json(res)
```

**Pull request closed without merging**
