### PR TITLE
Add helper function for rounding to step size

### PR DESCRIPTION
**Pull request by Kyzegs**

### CODE REVIEW

**Comment by kimchirichie** [comment]
nice method but it's not used anywhere

**Comment by Kyzegs** [comment]
Yeah, I get that. Maybe the `helpers.py` file is not the right location for it. I've seen people encountering issues when trying to round to specific step size, hence the function.

Would the `binance.py` file be a better place for this? Or do you think a function like this is obsolete?

**Comment by Unterarzt** [comment]
> nice method but it's not used anywhere

Yes it is. Almost every single pair has a different step size, and having to manually get the step size and rounding precision on every single pair is just straight infuriating.

**Comment by kimchirichie** [comment]
very well - i am convinced.

**Pull request merged**
