### PR TITLE
feat(client): add futures_mark_price_klines, futures_index_price_klines, futures_premium_index_klines

### PR DESCRIPTION
**Pull request by zhen1007**
Thank you for the excellent library!  
I noticed that the endpoint for **Mark Price Kline/Candlestick Data** is missing.  
You can refer to this link for more details: [Mark Price Kline/Candlestick Data](https://binance-docs.github.io/apidocs/futures/en/#mark-price-kline-candlestick-data)

### CODE REVIEW

**Comment by carlosmiei** [comment]
@zhen1007 Ended up adding futures_index_price_klines, futures_premium_index_klines as well 🙂

**Comment by zhen1007** [comment]
@carlosmiei  Perfect, thanks a lot!
When do you expect the new release to include this PR?

**Comment by carlosmiei** [comment]
@zhen1007 today or tomorrow at the latest

**Comment by carlosmiei** [comment]
@zhen1007 We just released a new version, update and let us know if anything!

**Pull request merged**
