### PR TITLE
Transfer asset in between spot and futures wallet

### PR DESCRIPTION
**Pull request by avatar-lavventura**
Related to https://github.com/sammchardy/python-binance/issues/626#issuecomment-753248332  

I verify that following change works

### CODE REVIEW

**Comment by kimchirichie** [comment]
i think this can already be done with `futures_account_transfer`

**Comment by kimchirichie** [comment]
```
futures_account_transfer(
  asset=asset,
  amount=amount,
  type=1  # 1 - to future
)
```

**Comment by avatar-lavventura** [comment]
@kimchirichie You are correct. sending `type=1` as argument transfer amount from spot to futures and sending `type=2` as argument transfers amount from futures to spot.

**Comment by kimchirichie** [comment]
closing because feature already exists as commented above

**Comment by efeint01** [comment]
thx guys

**Pull request closed without merging**
