### PR TITLE
Migrate from wapi to sapi

### LINKED ISSUE #768: Shift to Binance SAPI?
Binance just announced discontinuation of WAPI as of 1st August 2021, to be replaced by SAPI.
Link: https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269

### PR DESCRIPTION
**Pull request by AlexNik**
Migrate from WAPI to SAPI.

### WARNING!!! Breaking changes!!!

@sammchardy 
@kimchirichie 

Fix #768
Fix #780

### CODE REVIEW

**Comment by ttamg** [comment]
Hi @AlexNik .  Thanks for making this happen.  

The python API for this package doesn’t seem to change for requests, right?  

But some of the response bodies seem to have been updated as per your docstrings, correct?

**Comment by AlexNik** [comment]
@ttamg Some request parameters was changed (new parameters and some was renamed) and some response bodies was also changed.
I'll plan to update this PR for updating documentation files.

**Review by kimchirichie — APPROVED** [review]

**Comment by AlexNik** [comment]
@kimchirichie @ttamg I have update the docs.
I think I am finish.
@kimchirichie  @sammchardy  When we merge it we need to upgrade the version, because it is the breaking changes. What about 0.8.0?

**Comment by sammchardy** [comment]
I'm planning to release a v1.0.0 with the asyncio updates on the feature/asyncio branch.

It's close to done, will merge this into there as well.

**Comment by sammchardy** [comment]
Thanks @AlexNik and @kimchirichie

**Review by Brymes — COMMENTED** [review]
Thanks a Lot for implementing the changes this fast  @AlexNik @sammchardy.. Was kinda lost when i saw the mail from Binance. thanks for making this happen.. The commits seem good and Ready to go... I'd attempt testing  and report any bugs if found

**Pull request merged**
