### PR TITLE
Add spot parameter to get_historical_klines(...)

### PR DESCRIPTION
**Pull request by maxoja**

### CODE REVIEW

**Review by SteveChurch — APPROVED** [review]

**Comment by sammchardy** [comment]
thanks @maxoja

**Comment by maxoja** [comment]
Hi, I just notice that this PR is actually not a good idea

When someone wants to get historical prices from futures market, `futures_historical_klines(..)` should be use, not `get_historical_klines(spot=False)`. The problem is the name of `get_historical_klines(...)` is quite generic that one might think it's made for futures market while it's for spot market.

Sorry for not being thorough

**Comment by maxoja** [comment]
If you agree, you may revert the change and perhaps rename the function to be explicit

**Comment by AlexNik** [comment]
> 
> 
> If you agree, you may revert the change and perhaps rename the function to be explicit

A fixed it in #816

**Pull request merged**
