### PR TITLE
Isolated Margin endpoints and documentation

### PR DESCRIPTION
**Pull request by ttamg**
Hi there.

I needed the Isolation Margin endpoints (the current margin endpoints are mainly for cross-margin).

Broken this PR into a few commits to make it easier to review:
* Various docs improvements on the Margin page to make clear when cross-margin vs isolation margin is used - was a bit unclear before
* Some docstring fixes to add in isolation margin parameters which are now available on the Binance API
* Added various new isolation margin endpoints which were released by Binance.
* Updated the endpoints.md file for the new endpoints.

Other checks on my dev machine before pushing the commit:
* Endpoints tested to work against my own live cross-margin and isolation margin accounts on Binance.
* Tests (what there is of them) pass
* Docs build with Sphinx

### CODE REVIEW

**Comment by mfiro** [comment]
@ttamg great contribution! Regarding the last commit (Adding missing userDataStream in Endpoints.md):
You're right, I must have forgotten or missed them. Thanks for adding them:). However, I have noticed they are implemented on ```api/v1/userDataStream``` endpoint instead of  ```api/v3/userDataStream```. The latter one must be correct based on official doc. Could you please fix this (in case they are not working) or put a warning in the Endpoints.md documentation so that users are aware that these could be deprecated?

**Comment by ttamg** [comment]
Hi @mfiro  

On the V1 vs V3 issue on userDataStream.  I hadn't even noticed!  I've been using the existing python-binance codebase in production now for account websockets data (userDataStream).  It's been working perfectly fine on V1.

Digging into the code a bit more, It seems that userDataStream does ultimately use the correct V3, but the code could be made simpler.  Currently, 
* the user datastream calls the `def _post()` that uses the `PUBLIC_API_VERSION='v1'`
* BUT because `signed=True`, the `def _create_api_url(..)` switches the version to the  `PRIVATE_API_VERSION='v3'` 
* So it's ultimately correct and using `api/v3/`  

However I think this could all be simplified by just moving everything to `api/v3` as `api/v1` is deprecated rather than the confusion relying upon `signed=True`

Feels that this change is something more fundamental, and a quick code edit, but requires a lot of testing as it's a breaking change if it goes wrong!  Seems something for a separate PR.  Do you agree?

**Comment by mfiro** [comment]
Are you sure? I'm talking about these three methods:
```
client.stream_get_listen_key()
client.stream_keepalive(listenKey)
client.stream_close(listenKey)
```
For me these are implemented on v1 and their ```signed``` is ```False```. The issue shouldn't be solved by changing signed to True because this only should be used when a method needs a signature (those which have HMAC SHA256 next to their endpoint address)

I agree with you on the confusion. The things get worse when you know ```_request_api()``` has also a parameter ```version``` . I definitely agree that this part of the code needs a refactoring which should be carefully implemented and tested.

**Comment by ttamg** [comment]
Oh. I see what you mean on those endpoints.  You are right.

I can say that I am currently using those in production and they work fine on v1 currently.  

What do you suggest for tweaking those?
- Moving them to v3 looks like it needs a bit of refactoring and I'm uncomfortable doing something so fundamental myself, particularly in this branch.
- Adding a warning to them . do you have a suggestion of how to do that?  I can add into the code
- Leave it for now and raise an issue for this separately.

Let me know what you think.

**Comment by mfiro** [comment]
There are also other endpoints like this, stated as deprecated on v1 but still working. I appreciate your solutions, however, @kimchirichie can decide on this. He's the current maintainer.

**Comment by kimchirichie** [comment]
its additive, something is better than nothing. if theres a future branch to improve i will also consider merging

**Pull request merged**
